name: Node.js Build and test
on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      - run: pnpm test run
